### ISSUE TITLE
Unable to sync with Radarr

### ISSUE THREAD

**Issue by indecline** [recyclarr/recyclarr#140]
Hiiiii,

Love the project! My Sonarr is working fine but for some reason I'm unable to sync with Radarr. Any assistance would be much appreciated, don't think I've configured it incorrectly?

`
/ $ recyclarr radarr
[INF] Processing server http://hostname:7878/radarr
[INF] Processing Quality Definition: movie
[INF] Number of updated qualities: 0

HTTP error while communicating with Radarr: Flurl.Http.FlurlHttpException: Call failed with status code 500 (Internal Server Error): POST http://hostname:7878/radarr/api/v3/customformat?apikey=SNIP
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at TrashLib.Services.CustomFormat.Api.CustomFormatService.CreateCustomFormat(ProcessedCustomFormatData cf) in D:\a\recyclarr\recyclarr\src\TrashLib\Services\CustomFormat\Api\CustomFormatService.cs:line 27
   at TrashLib.Services.CustomFormat.Processors.PersistenceSteps.CustomFormatApiPersistenceStep.Process(ICustomFormatService api, CustomFormatTransactionData transactions) in D:\a\recyclarr\recyclarr\src\TrashLib\Services\CustomFormat\Processors\PersistenceSteps\CustomFormatApiPersistenceStep.cs:line 11
   at TrashLib.Services.CustomFormat.Processors.PersistenceProcessor.PersistCustomFormats(IReadOnlyCollection`1 guideCfs, IEnumerable`1 deletedCfsInCache, IDictionary`2 profileScores) in D:\a\recyclarr\recyclarr\src\TrashLib\Services\CustomFormat\Processors\PersistenceProcessor.cs:line 63
   at TrashLib.Services.CustomFormat.CustomFormatUpdater.Process(Boolean isPreview, IEnumerable`1 configs, IGuideService guideService) in D:\a\recyclarr\recyclarr\src\TrashLib\Services\CustomFormat\CustomFormatUpdater.cs:line 53
   at Recyclarr.Command.RadarrCommand.Process(IServiceLocatorProxy container) in D:\a\recyclarr\recyclarr\src\Recyclarr\Command\RadarrCommand.cs:line 68
   at Recyclarr.Command.RadarrCommand.Process(IServiceLocatorProxy container) in D:\a\recyclarr\recyclarr\src\Recyclarr\Command\RadarrCommand.cs:line 68
   at Recyclarr.Command.BaseCommand.ExecuteAsync(IConsole console) in D:\a\recyclarr\recyclarr\src\Recyclarr\Command\BaseCommand.cs:line 62
   at Recyclarr.Command.ServiceCommand.ExecuteAsync(IConsole console) in D:\a\recyclarr\recyclarr\src\Recyclarr\Command\ServiceCommand.cs:line 48
`

**Comment by rcdailey** [comment]
Hello, thanks for writing in. Before I help, I'd like to make a few requests:

1. In the future, please use the [discussions](https://github.com/recyclarr/recyclarr/discussions) tab to ask questions.
2. When posting logs or other long text walls, please use [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks). This will make it much easier to read.

With that out of the way, on to your problem. Unfortunately from what you've provided, it's not possible to know what the issue is. Here's what I'd recommend:

- Make sure the URL you are providing is reachable: Try hitting it with your browser and see what happens. The expected behavior: You should see Radarr load up.
- Double check your API key is correct.
- Dig into the Radarr logs and find the corresponding logs and provide those here. That should tell us more.
- Provide your redacted `recyclarr.yml` here for review along with your latest Recyclarr log file.

**Comment by indecline** [comment]
Thanks for the fenced code block tip! Have edited my post and apologies for posting in the wrong section.

Have triple checked the URL and API key and they are correct.

I believe this is the relevant Radarr log below and I've attached my recyclarr.yml

```
2022-11-01 08:53:30.9|Fatal|RadarrErrorPipeline|Request Failed. POST /api/v3/customformat

[v4.1.0.6175] System.NullReferenceException: Object reference not set to an instance of an object.
   at Radarr.Api.V3.CustomFormats.CustomFormatResourceMapper.MapSpecification(CustomFormatSpecificationSchema resource, List`1 specifications) in D:\a\1\s\src\Radarr.Api.V3\CustomFormats\CustomFormatResource.cs:line 50
   at Radarr.Api.V3.CustomFormats.CustomFormatResourceMapper.<>c__DisplayClass2_0.<ToModel>b__0(CustomFormatSpecificationSchema x) in D:\a\1\s\src\Radarr.Api.V3\CustomFormats\CustomFormatResource.cs:line 44
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Radarr.Api.V3.CustomFormats.CustomFormatResourceMapper.ToModel(CustomFormatResource resource, List`1 specifications) in D:\a\1\s\src\Radarr.Api.V3\CustomFormats\CustomFormatResource.cs:line 39
   at Radarr.Api.V3.CustomFormats.CustomFormatController.Create(CustomFormatResource customFormatResource) in D:\a\1\s\src\Radarr.Api.V3\CustomFormats\CustomFormatController.cs:line 38
   at lambda_method103(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```
Thanks for the assistance!

[recyclarr.txt](https://github.com/recyclarr/recyclarr/files/9904642/recyclarr.txt)

**Comment by rcdailey** [comment]
What version of Recyclarr are you using?
What version of Radarr are you using?

**Comment by indecline** [comment]
> What version of Recyclarr are you using? What version of Radarr are you using?

I was running the below in containers.

Recyclarr: 2.6.1
Radarr: 4.1.0.6175

Apologies I thought my Radarr was up to date but turns out it wasn't. Updated to 4.2.4.6635 and it's working great now!

Thanks for the assistance.
