### ISSUE TITLE
Config folder gets created with root rights

### ISSUE THREAD

**Issue by davidbalint** [recyclarr/recyclarr#195]
Hello, I get the following error in the logs 

  at async Task<int> Execute(IConfiguration configuration, IEnumerable<string>  
     args) in CommandExecutor.cs:85                                             
  at async Task<int> RunAsync(IEnumerable<string> args) in CommandApp.cs:84     
  at int Run(IEnumerable<string> args) in CommandApp.cs:58                      
  at int Main(string[] args) in Program.cs:54                                   
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/config/settings.yml' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.FileInfo.CreateText()
   at System.IO.Abstractions.FileInfoWrapper.CreateText()
   at Recyclarr.TrashLib.Settings.SettingsProvider.CreateDefaultSettingsFile() in /home/runner/work/recyclarr/recyclarr/src/Recyclarr.TrashLib/Settings/SettingsProvider.cs:line 62
   at Recyclarr.TrashLib.Settings.SettingsProvider.LoadOrCreateSettingsFile(IYamlSerializerFactory serializerFactory) in /home/runner/work/recyclarr/recyclarr/src/Recyclarr.TrashLib/Settings/SettingsProvider.cs:line 30
   at Recyclarr.TrashLib.Settings.SettingsProvider.<>c__DisplayClass5_0.<.ctor>b__0() in /home/runner/work/recyclarr/recyclarr/src/Recyclarr.TrashLib/Settings/SettingsProvider.cs:line 22
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Recyclarr.TrashLib.Settings.SettingsProvider.get_Settings() in /home/runner/work/recyclarr/recyclarr/src/Recyclarr.TrashLib/Settings/SettingsProvider.cs:line 12
   at Recyclarr.Cli.Console.Setup.JanitorCleanupTask.OnFinish() in /home/runner/work/recyclarr/recyclarr/src/Recyclarr.Cli/Console/Setup/JanitorCleanupTask.cs:line 26
   at Recyclarr.Cli.Program.<>c.<OnAppCleanup>b__5_0(IBaseCommandSetupTask x) in /home/runner/work/recyclarr/recyclarr/src/Recyclarr.Cli/Program.cs:line 91
   at SuperLinq.SuperEnumerable.ForEach[TSource](IEnumerable`1 source, Action`1 action)
   at Recyclarr.Cli.Program.OnAppCleanup() in /home/runner/work/recyclarr/recyclarr/src/Recyclarr.Cli/Program.cs:line 91
   at Recyclarr.Cli.Program.Main(String[] args) in /home/runner/work/recyclarr/recyclarr/src/Recyclarr.Cli/Program.cs:line 69
/entrypoint.sh: line 8:     8 Aborted                 (core dumped) recyclarr config create

I added this to my existing docker-compose where other *arr apps run without problems:
 recyclarr:
    image: recyclarr/recyclarr
    container_name: recyclarr
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/${USERNAME}/serverconfig/recyclarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - RECYCLARR_CREATE_CONFIG=true
      
  Also tried with the reccomended "user: 1000:1000" but same problem

**Comment by rcdailey** [comment]
Firstly, even if this was a bug, you decided to completely ignore the issue template. I will not provide support to people that do this.

Secondly, this isn't a bug but a request for support. The Discussions tab exists for these.

Thirdly, your issue is due to not following the instructions in the documentation. Please review the installation documentation to find your answer.

**Comment by davidbalint** [comment]
Thanks for the tips, the template asks for files that do not get generated, so it's impossible to follow it in my case.

Have a nice day!
