### ISSUE TITLE
No configuration YAML files found

### ISSUE THREAD

**Issue by jgdf42** [recyclarr/recyclarr#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

C:\Users\ThinkCentre\Downloads\recyclarr-win-x64>recyclarr sync
[INF] Cloning 'trash-guides' repository...
[ERR] Exception: No configuration YAML files found

### Expected Behavior

Sync doesn't work.

### Steps To Reproduce

run recyclarr sync in an elevated cmd prompt

### Environment & Versions

```bash
- Operating System: win10 22h2
- Architecture: x64
- Recyclarr Version: 5.1.1
- Recyclarr Build: 5.1.1+Branch.tags-v5.1.1.Sha.4d0ce0d09f367ce2520eca53c4043568efa328fd
- Sonarr Version: 3.0.10.1567
- Radarr Version: 4.6.4.7568
```

### Recyclarr Log File(s)

[21:00:11 DBG] Recyclarr Version: 5.1.1+Branch.tags-v5.1.1.Sha.4d0ce0d09f367ce2520eca53c4043568efa328fd
[21:00:11 DBG] App Data Dir: C:\Users\ThinkCentre\AppData\Roaming\recyclarr
[21:00:11 DBG] Using Branch & Clone URL: master, https://github.com/TRaSH-Guides/Guides.git
[21:00:11 INF] Cloning 'trash-guides' repository...
[21:00:11 DBG] Executing git command with args: ["clone","-b","master","https://github.com/TRaSH-Guides/Guides.git","."]
[21:00:11 DBG] Using working directory: C:\Users\ThinkCentre\AppData\Roaming\recyclarr\repositories\trash-guides
[21:00:31 DBG] Command Output: 
[21:00:31 DBG] Executing git command with args: ["remote","set-url","origin","https://github.com/TRaSH-Guides/Guides.git"]
[21:00:31 DBG] Using working directory: C:\Users\ThinkCentre\AppData\Roaming\recyclarr\repositories\trash-guides
[21:00:31 DBG] Command Output: 
[21:00:31 DBG] Remote 'origin' set to https://github.com/TRaSH-Guides/Guides.git
[21:00:31 DBG] Executing git command with args: ["checkout","-f","master"]
[21:00:31 DBG] Using working directory: C:\Users\ThinkCentre\AppData\Roaming\recyclarr\repositories\trash-guides
[21:00:32 DBG] Command Output: Your branch is up to date with 'origin/master'.
[21:00:32 DBG] Executing git command with args: ["fetch","origin"]
[21:00:32 DBG] Using working directory: C:\Users\ThinkCentre\AppData\Roaming\recyclarr\repositories\trash-guides
[21:00:32 DBG] Command Output: 
[21:00:32 DBG] Executing git command with args: ["reset","--hard","origin/master"]
[21:00:32 DBG] Using working directory: C:\Users\ThinkCentre\AppData\Roaming\recyclarr\repositories\trash-guides
[21:00:33 DBG] Command Output: HEAD is now at 110fce99 style(guides): renamed click to expand to click to show/hide (#1474)
[21:00:33 ERR] Exception
Recyclarr.TrashLib.Config.Parsing.ErrorHandling.NoConfigurationFilesException: No configuration YAML files found
   at Recyclarr.TrashLib.Config.Parsing.ConfigurationFinder.GetConfigFiles(IReadOnlyCollection`1 configs) in D:\a\recyclarr\recyclarr\src\Recyclarr.TrashLib\Config\Parsing\ConfigurationFinder.cs:line 47
   at Recyclarr.Cli.Processors.Sync.SyncProcessor.ProcessConfigs(ISyncSettings settings) in D:\a\recyclarr\recyclarr\src\Recyclarr.Cli\Processors\Sync\SyncProcessor.cs:line 45
[21:00:33 DBG] Cleaning up logs using max files of 20

### Configuration YAML

```YAML
Doesn't exist.
```

**Comment by rcdailey** [comment]
Please read the wiki for installation instructions, as well as the configuration you're **required** to have.
