### ISSUE TITLE
Can't run the script

### ISSUE THREAD

**Issue by Gylesie** [recyclarr/recyclarr#75]
When running recyclarr sonarr or recyclarr radarr, I'm getting following error:

```
Performing migration steps...
[ERR] An exception occurred during git operations on path: /root/.config/recyclarr/repo
LibGit2Sharp.LibGit2SharpException: could not load ssl libraries
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts) in /_/LibGit2Sharp/Core/Proxy.cs:line 278
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options) in /_/LibGit2Sharp/Repository.cs:line 793
   at VersionControl.Wrappers.LibGit2SharpRepositoryStaticWrapper.Clone(String sourceUrl, String workdirPath, CloneOptions options) in D:\a\recyclarr\recyclarr\src\VersionControl\Wrappers\LibGit2SharpRepositoryStaticWrapper.cs:line 8
   at VersionControl.GitRepositoryFactory.DeleteAndCloneRepo(String repoUrl, String repoPath, String branch) in D:\a\recyclarr\recyclarr\src\VersionControl\GitRepositoryFactory.cs:line 42
   at VersionControl.GitRepositoryFactory.CreateAndCloneIfNeeded(String repoUrl, String repoPath, String branch) in D:\a\recyclarr\recyclarr\src\VersionControl\GitRepositoryFactory.cs:line 27
   at TrashLib.Repo.RepoUpdater.CheckoutAndUpdateRepo() in D:\a\recyclarr\recyclarr\src\TrashLib\Repo\RepoUpdater.cs:line 59
[INF] Deleting local git repo and retrying git operation...
Segmentation fault (core dumped)
```

**Comment by rcdailey** [comment]
Please review the Troubleshooting page on the wiki.

**Comment by Gylesie** [comment]
sorry, thanks for the info
