### ISSUE TITLE
FlurlHttpException: 401

### ISSUE THREAD

**Issue by urwrstkn8mare** [recyclarr/recyclarr#88]
I can't figure out what's wrong here: (`recyclarr radarr`)
```
[INF] Processing server http://hostname:17878
[INF] Processing Quality Definition: Movie
[INF] Number of updated qualities: 0

[INF] All custom formats are already up to date!
[INF] All quality profile scores are already up to date!
[INF] Processing server http://hostname:7878
[INF] Processing Quality Definition: Movie
HTTP error while communicating with Radarr: Flurl.Http.FlurlHttpException: Call failed with status code 401 (Unauthorized): GET http://hostname:7878/api/v3/qualitydefinition?apikey=SNIP
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at TrashLib.Radarr.QualityDefinition.Api.QualityDefinitionService.GetQualityDefinition() in D:\a\recyclarr\recyclarr\src\TrashLib\Radarr\QualityDefinition\Api\QualityDefinitionService.cs:line 19
   at TrashLib.Radarr.QualityDefinition.RadarrQualityDefinitionUpdater.ProcessQualityDefinition(IEnumerable`1 guideQuality) in D:\a\recyclarr\recyclarr\src\TrashLib\Radarr\QualityDefinition\RadarrQualityDefinitionUpdater.cs:line 73
   at TrashLib.Radarr.QualityDefinition.RadarrQualityDefinitionUpdater.Process(Boolean isPreview, RadarrConfiguration config) in D:\a\recyclarr\recyclarr\src\TrashLib\Radarr\QualityDefinition\RadarrQualityDefinitionUpdater.cs:line 53
   at Recyclarr.Command.Services.RadarrService.Process(IRadarrCommand cmd) in D:\a\recyclarr\recyclarr\src\Recyclarr\Command\Services\RadarrService.cs:line 47
   at Recyclarr.Command.Services.ServiceBase`1.Execute(T cmd) in D:\a\recyclarr\recyclarr\src\Recyclarr\Command\Services\ServiceBase.cs:line 18
```

Running it with `--preview` throws no errors.

**Comment by rcdailey** [comment]
HTTP 401 means "Unauthorized". Can you verify that your API Key is correct?

Also `--preview` does not actively connect to Sonarr/Radarr, it only reads the guide data. So I don't expect that you would see the issue when using it.

**Comment by rcdailey** [comment]
Closing due to lack of response from OP.
