### ISSUE TITLE
Error when trying to run against second Radarr instance

### ISSUE THREAD

**Issue by jpoll** [recyclarr/recyclarr#89]
I am trying to run recyclarr against a second radarr instance using a different config file but it fails with the following error. 

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at TrashLib.Radarr.CustomFormat.Processors.GuideSteps.QualityProfileStep.Process(IEnumerable`1 configData) in D:\a\recyclarr\recyclarr\src\TrashLib\Radarr\CustomFormat\Processors\GuideSteps\QualityProfileStep.cs:line 17
   at TrashLib.Radarr.CustomFormat.Processors.GuideProcessor.BuildGuideDataAsync(IReadOnlyCollection`1 config, CustomFormatCache cache) in D:\a\recyclarr\recyclarr\src\TrashLib\Radarr\CustomFormat\Processors\GuideProcessor.cs:line 77
   at TrashLib.Radarr.CustomFormat.CustomFormatUpdater.Process(Boolean isPreview, RadarrConfiguration config) in D:\a\recyclarr\recyclarr\src\TrashLib\Radarr\CustomFormat\CustomFormatUpdater.cs:line 34
   at Recyclarr.Command.Services.RadarrService.Process(IRadarrCommand cmd) in D:\a\recyclarr\recyclarr\src\Recyclarr\Command\Services\RadarrService.cs:line 52
   at Recyclarr.Command.Services.ServiceBase`1.Execute(T cmd) in D:\a\recyclarr\recyclarr\src\Recyclarr\Command\Services\ServiceBase.cs:line 18
```

[recyclarr4k.txt](https://github.com/recyclarr/recyclarr/files/8921964/recyclarr4k.txt)
[trash_2022-06-16_14-58-21.log](https://github.com/recyclarr/recyclarr/files/8921949/trash_2022-06-16_14-58-21.log)

**Comment by rcdailey** [comment]
I found the bug and have fixed it. It will be in the next release.

For now, the workaround is to not have an empty list for `quality_profiles`. Either remove it or add a quality profile under it.
